# Configure various parameters for converting grapecity format to Alignments format
# Used by grapecity.Manager
# Organized by target version: this only needs to cover a limited number of alignments.

# This file is used to drive generating alignment data, so don't
# include values for which there is no data.

### language = eng

[CSBE]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[CSBE.WLC]

jsonfile = "csbe.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[CSBE.NA28]

jsonfile = "csbe.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[ELT]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[ELT.WLC]

jsonfile = "elt.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[ELT.NA28]

jsonfile = "elt.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[ESV]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[ESV.WLC]

jsonfile = "esv.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[ESV.NA28]

jsonfile = "esv.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[HCSB]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[HCSB.WLC]

jsonfile = "hcsb.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[HCSB.NA28]

jsonfile = "hcsb.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[KJV]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[KJV.WLC]

jsonfile = "kjv.ot.alignment.json"
omitsourcetext = false
omittargettext = false

[KJV.NA28]

jsonfile = "kjv.nt.alignment.json"
omitsourcetext = true
omittargettext = false

[LEB]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[LEB.WLC]

jsonfile = "leb.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[LEB.NA28]

jsonfile = "leb.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NASB77]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NASB77.WLC]

jsonfile = "nasb77.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NASB77.NA28]

jsonfile = "nasb77.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NASB95]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NASB95.WLC]

jsonfile = "nasb95.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NASB95.NA28]

jsonfile = "nasb95.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NET]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NET.WLC]

jsonfile = "net.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NET.NA28]

jsonfile = "net.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NET2]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NET2.WLC]

jsonfile = "net2.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NET2.NA28]

jsonfile = "net2.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NIV11]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NIV11.WLC]

jsonfile = "niv11.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NIV11.NA28]

jsonfile = "niv11.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NIV84]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NIV84.WLC]

jsonfile = "niv84.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NIV84.NA28]

jsonfile = "niv84.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NKJV]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NKJV.WLC]

jsonfile = "nkjv.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NKJV.NA28]

jsonfile = "nkjv.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[NRSV]

targetlang = "eng"
ot_source = "WLC"
nt_source = "NA28"

[NRSV.WLC]

jsonfile = "nrsv.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[NRSV.NA28]

jsonfile = "nrsv.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[YLT]

targetlang = "eng"
ot_source = "WLC"
nt_source = "SBLGNT"
# nt_source = "NA28"

[YLT.WLC]

jsonfile = "ylt.ot.alignment.json"
omitsourcetext = false
omittargettext = false

[YLT.SBLGNT]

jsonfile = "ylt.nt.alignment.json"
omitsourcetext = true
omittargettext = false

## THIS FAR

### 
# SLI says language = cmn, not 'man'

[CUVMP]

targetlang = "man"
ot_source = "WLC"
nt_source = "NA28"

[CUVMP.WLC]

jsonfile = "cuvmp.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[CUVMP.NA28]

jsonfile = "cuvmp.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[SGS]

targetlang = "man"
ot_source = "WLC"
nt_source = "NA28"

[SGS.WLC]

jsonfile = "sgs.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[SGS.NA28]

jsonfile = "sgs.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[XYB]

targetlang = "man"
ot_source = "WLC"
nt_source = "NA28"

[XYB.WLC]

jsonfile = "xyb.ot.alignment.json"
omitsourcetext = false
omittargettext = true

[XYB.NA28]

jsonfile = "xyb.nt.alignment.json"
omitsourcetext = true
omittargettext = true

### language = hin

[HOVR]

# Hindi Old Version, Re-edited: under copyright

targetlang = "hin"
ot_source = "WLC"
nt_source = "NA28"

[HOVR.WLC]

jsonfile = "hovrOT.ot.alignment.json"
omitsourcetext = false
omittargettext = true


[HOVR.NA28]

jsonfile = "hovrNT.nt.alignment.json"
omitsourcetext = true
omittargettext = true

[HSB]

targetlang = "hin"
ot_source = "WLC"
nt_source = "NA28"

# No GrapeCity data for this
# [HSB.WLC]

# jsonfile = "hsb.ot.alignment.json"
# omitsourcetext = false
# omittargettext = true

[HSB.NA28]

jsonfile = "hsb.nt.alignment.json"
omitsourcetext = true
omittargettext = true


### language = jpn

### language = khm

### language = mya

[JVB]

targetlang = "mya"
# only NT available in GrapeCity data
nt_source = "NA28"

[JVB.NA28]

jsonfile = "jvbnt.nt.alignment.json"
omitsourcetext = true
omittargettext = false

[MCL]

targetlang = "mya"
ot_source = "WLC"
nt_source = "NA28"

[MCL.WLC]

jsonfile = "mclot.ot.alignment.json"
omitsourcetext = false
omittargettext = false

[MCL.NA28]

jsonfile = "mclnt.nt.alignment.json"
omitsourcetext = true
omittargettext = false


